### ISSUE TITLE
pyo synth error

### ISSUE THREAD

**Issue by benyaminmk** [benyaminmk/neuromusic#3]
# 🐛 Error when running `pyo_synth.py`
When I tried running `pyo_synth.py` from windows subsystem for linux I got the following error message:

> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM sysdefault
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.front
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround21
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround40
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround41
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround50
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround51
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.surround71
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM default
> ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
> ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
> ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
> ALSA lib conf.c:4568:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
> ALSA lib conf.c:5047:(snd_config_expand) Evaluate error: No such file or directory
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM dmix
> Segmentation fault

## ways to resolve
My suspicion is that this is a result of running `pyo_synth.py` from WSL because I don't have xserver working yet for gui functionality. @dcardonab Does this scipt pop up a gui when run? 

### TODO
- [x] @benyaminmk run on linux desktop rather than windows laptop to see if issue is resolved.

**Comment by benyaminmk** [comment]
# :bug: Different bug on linux desktop
When run on my linux desktop I get a different error message related to the pyo `Server`

## Error message
> ALSA lib conf.c:3558:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib/alsa-lib/libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
> ALSA lib control.c:1375:(snd_ctl_open_noupdate) Invalid CTL hw:0
> ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
> ALSA lib pcm.c:2565:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
> ALSA lib pcm_route.c:869:(find_matching_chmap) Found no matching channel map
> ALSA lib dlmisc.c:287:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so ((null): /usr/lib/alsa-lib/libasound_module_pcm_pulse.so: cannot open shared object file: No such file or directory)
> ALSA lib dlmisc.c:287:(snd1_dlobj_cache_get) Cannot open shared library /usr/lib/alsa-lib/libasound_module_pcm_pulse.so ((null): /usr/lib/alsa-lib/libasound_module_pcm_pulse.so: cannot open shared object file: No such file or directory)
> ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
> ALSA lib pcm_dmix.c:1108:(snd_pcm_dmix_open) unable to open slave
> Pyo warning: Portaudio output device `sysdefault` has fewer channels (0) than requested (2).
> Portaudio error in Pa_OpenStream: Invalid number of channels
> Pyo error: From portaudio, Invalid number of channels
> Portaudio error in Pa_CloseStream (pa_deinit): PortAudio not initialized
> Portaudio error in Pa_Terminate (pa_deinit): PortAudio not initialized
> Pyo error: 
> Server not booted.
> ALSA lib conf.c:3558:(snd_config_hooks_call) Cannot open shared library libasound_module_conf_pulse.so (/usr/lib/alsa-lib/libasound_module_conf_pulse.so: libasound_module_conf_pulse.so: cannot open shared object file: No such file or directory)
> ALSA lib seq.c:935:(snd_seq_open_noupdate) Unknown SEQ default
> Pyo warning: Portmidi warning: no midi device found!
> Portmidi closed.
> Pyo warning: The Server must be booted before calling the start method!
> Traceback (most recent call last):
>   File "pyo_synth.py", line 19, in <module>
>     env = Adsr(attack=1, release=2, dur=0, mul=1)  # Env with soft attack and release, undetermined duration, and amplitude mult at full gain
>   File "/home/benmk/miniconda3/envs/muse/lib/python3.8/site-packages/pyo/lib/controls.py", line 278, in __init__
>     PyoObject.__init__(self, mul, add)
>   File "/home/benmk/miniconda3/envs/muse/lib/python3.8/site-packages/pyo/lib/_core.py", line 1201, in __init__
>     PyoObjectBase.__init__(self)
>   File "/home/benmk/miniconda3/envs/muse/lib/python3.8/site-packages/pyo/lib/_core.py", line 889, in __init__
>     raise PyoServerStateException("The Server must be booted before "
> pyo.lib._core.PyoServerStateException: The Server must be booted before creating any audio object.

**Comment by benyaminmk** [comment]
linux desktop error could be dependency related. 

current envrionment for this project: 

```
# packages in environment at /home/benmk/miniconda3/envs/muse:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
abseil-cpp                20200225.2           he1b5a44_0    conda-forge
alsa-lib                  1.1.5             h516909a_1002    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
apptools                  4.5.0                      py_0    conda-forge
arrow-cpp                 0.16.0           py38h908f8fe_2    conda-forge
astroid                   2.3.3                    py38_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
aws-sdk-cpp               1.7.164              hc831370_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bitstring                 3.1.6                    pypi_0    pypi
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
blosc                     1.18.1               he1b5a44_0    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
brotli                    1.0.7             he1b5a44_1001    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
c-ares                    1.15.0            h516909a_1001    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
certifi                   2020.4.5.2       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38hd463f26_0    conda-forge
cftime                    1.1.3            py38h8790de6_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              2.9.2            py38h766eaa4_0    conda-forge
curl                      7.69.1               h33f0ec9_0    conda-forge
cvxopt                    1.2.5            py38hf48cded_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.19                  pypi_0    pypi
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
dipy                      1.1.0            py38hc1659b7_1    conda-forge
distro                    1.5.0              pyh9f0ad1d_0    conda-forge
dsdp                      5.8               h23d7751_1203    conda-forge
entrypoints               0.3             py38h32f6830_1001    conda-forge
enum-compat               0.0.3                    pypi_0    pypi
envisage                  4.9.2                      py_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
feather-format            0.4.0                   py_1003    conda-forge
fftw                      3.3.8           nompi_h7f3a6c3_1110    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
future                    0.18.2           py38h32f6830_1    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gflags                    2.2.2             he1b5a44_1002    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.58.3          py38h73cb85d_1004    conda-forge
glog                      0.4.0                h49b9bf7_3    conda-forge
glpk                      4.65              he80fd80_1002    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
grpc-cpp                  1.28.1               h8e748ff_2    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gst-plugins-base          1.14.5               h0935bb2_2    conda-forge
gstreamer                 1.14.5               h36ae1b5_2    conda-forge
h5py                      2.10.0          nompi_py38h513d04c_102    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
importlib-metadata        1.6.0            py38h32f6830_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
ipykernel                 5.3.0            py38h23f93f0_0    conda-forge
ipython                   7.13.0           py38h32f6830_2    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21           py38h32f6830_1    conda-forge
jedi                      0.16.0           py38h32f6830_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsoncpp                   1.8.4             hc9558a2_1002    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_console           6.1.0                      py_1    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
kiwisolver                1.2.0            py38hbf85e49_0    conda-forge
krb5                      1.17.1               h2fd8d38_0    conda-forge
lazy-object-proxy         1.4.3            py38h1e0a361_2    conda-forge
lcms2                     2.9                  hbd6801e_2    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libclang                  9.0.1           default_hde54327_0    conda-forge
libcurl                   7.69.1               hf7181ac_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libevent                  2.1.10               h72c5cf5_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libllvm9                  9.0.1                hc9558a2_0    conda-forge
libnetcdf                 4.7.4           nompi_h9f9fd6a_101    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libprotobuf               3.11.4               h8b12597_0    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxkbcommon              0.10.0               he1b5a44_0    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
llvmlite                  0.32.1           py38hd408876_0  
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
markupsafe                1.1.1            py38h1e0a361_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py38h2af1d28_0    conda-forge
mayavi                    4.7.1            py38h7eb8c7e_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
meshio                    4.0.13                     py_0    conda-forge
metis                     5.1.0             he1b5a44_1005    conda-forge
mistune                   0.8.4           py38h1e0a361_1001    conda-forge
mne                       0.20.5           py38h32f6830_0    conda-forge
mock                      4.0.2            py38h32f6830_0    conda-forge
nbconvert                 5.6.1            py38h32f6830_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.5.3           nompi_py38heb6102f_103    conda-forge
networkx                  2.4                      pypi_0    pypi
nibabel                   3.1.0                      py_0    conda-forge
nilearn                   0.6.2              pyh5ca1d4c_0    conda-forge
nitime                    0.8.1                    pypi_0    pypi
notebook                  6.0.3            py38h32f6830_0    conda-forge
nspr                      4.25                 he1b5a44_0    conda-forge
nsrl                      0.1.1                    pypi_0    pypi
nss                       3.47                 he751ad9_0    conda-forge
numba                     0.49.1           py38h0573a6f_0  
numexpr                   2.7.1            py38hcb8c335_1    conda-forge
numpy                     1.18.1           py38h8854b6b_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openjdk                   11.0.1            h600c080_1018    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandas                    1.0.3            py38hcb8c335_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.6.2                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0            py38h32f6830_1    conda-forge
pickleshare               0.7.5           py38h32f6830_1001    conda-forge
pillow                    7.1.2            py38h9776b28_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
prompt_toolkit            3.0.5                         0    conda-forge
psutil                    5.7.0            py38h1e0a361_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyarrow                   0.16.0           py38h56ab25f_2    conda-forge
pycparser                 2.20                       py_0    conda-forge
pydicom                   1.4.2                      py_0    conda-forge
pyface                    6.1.2                      py_0    conda-forge
pygatt                    4.0.5                    pypi_0    pypi
pygments                  2.6.1                      py_0    conda-forge
pylint                    2.4.4                    py38_0    conda-forge
pylsl                     1.12.2                   pypi_0    pypi
pyo                       1.0.2                    pypi_0    pypi
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.12.3           py38hcca6a23_1    conda-forge
pyqt5-sip                 4.19.18                  pypi_0    pypi
pyqtwebengine             5.12.1                   pypi_0    pypi
pyrsistent                0.16.0           py38h1e0a361_0    conda-forge
pyserial                  3.4                      pypi_0    pypi
pysocks                   1.7.1            py38h32f6830_1    conda-forge
pysurfer                  0.10.0                     py_0    conda-forge
pytables                  3.6.1            py38h9f153d1_1    conda-forge
python                    3.8.2           h8356626_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-picard             0.4                pyh5ca1d4c_1    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2019.3                     py_0    conda-forge
pyvista                   0.24.2                     py_0    conda-forge
pyzmq                     19.0.1           py38ha71036d_0    conda-forge
qt                        5.12.5               hd8c4c69_1    conda-forge
qtconsole                 4.7.4              pyh9f0ad1d_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
re2                       2020.04.01           he1b5a44_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
scikit-learn              0.22.2.post1     py38hcdab131_0    conda-forge
scipy                     1.4.1            py38h18bccfc_2    conda-forge
scooby                    0.5.4              pyh9f0ad1d_0    conda-forge
seaborn                   0.10.0                     py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
six                       1.14.0                     py_1    conda-forge
snappy                    1.1.8                he1b5a44_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
statsmodels               0.11.1           py38h1e0a361_1    conda-forge
suitesparse               5.7.2                h717dc36_0    conda-forge
tabula-py                 1.4.1            py38h32f6830_1    conda-forge
tbb                       2020.1               hc9558a2_0    conda-forge
terminado                 0.8.3            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.13.0               h62aa4f2_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py38h1e0a361_1    conda-forge
tqdm                      4.46.0             pyh9f0ad1d_0    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
traits                    6.0.0            py38h1e0a361_1    conda-forge
traitsui                  6.1.3                      py_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
vtk                       8.2.0           py38h667666d_213    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
widgetsnbextension        3.5.1                    py38_0    conda-forge
wrapt                     1.12.1           py38h1e0a361_1    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-fixesproto           5.0               h14c3975_1002    conda-forge
xorg-inputproto           2.3.2             h14c3975_1002    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxfixes            5.0.3             h516909a_1004    conda-forge
xorg-libxi                1.7.10               h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.2.0                h516909a_0    conda-forge
xorg-libxtst              1.2.3             h516909a_1002    conda-forge
xorg-recordproto          1.14.2            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h516909a_1002    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_2    conda-forge
```

**Comment by dcardonab** [comment]
i did some digging a found that there are a couple of steps to run pyo on a conda env. i used these instructions. it worked for me by following the macOS homebrew instructions, but since you are not on mac, step 1 might be a bit different for you, and the compiling pyo from sources documentation page seems to have some info regarding ubuntu and windows. i hope it works for you!

anyway, here are the instructions:

1.  Use the compiling from source instructions for macOS using Homebrew here:
http://ajaxsoundstudio.com/pyodoc/compiling.html

1A. So you need to install Homebrew so you can run the first line.
brew install liblo libsndfile portaudio portmidi

1B.  Fix any warnings you get from HomeBrew.   Specifically, I had to force relink the files.  Homebrew should tell you what to do if you have to do that.

2.  Clone the Git Depot and go to the PyO directory.
git clone https://github.com/belangeo/pyo.git
cd pyo

3.  IMPORTANT STEP:  Activate the correct Anaconda  environment, from the command line with 'conda'.  You can find instructions on how to do that here:

https://conda.io/docs/user-guide/tasks/manage-environments.html?highlight=activate#managing-environments

If you are not using environments in Anaconda then don't worry.   But you have to do this for every environment  in Anaconda you want to use PyO in.

4.  Build PyO
python setup.py install --use-coreaudio --use-double

**Comment by benyaminmk** [comment]
pip installing pyo in a clean environment in windows worked so I'm closing this
