### ISSUE TITLE
conda create issue

### ISSUE THREAD

**Issue by dcardonab** [benyaminmk/neuromusic#4]
I seem to be running into issues when trying to create a conda env from the requirements.txt file. This is the log I get. Perhaps you have a better idea?

Davids-MBP-7:neuromusic David$ conda create --name neuroMusic --file requirements.txt
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - markupsafe==1.1.1=py38h1e0a361_1
  - nitime==0.8.1=pypi_0
  - boost-cpp==1.72.0=h8e57a91_0
  - gsl==2.6=h294904e_0
  - pillow==7.1.2=py38h9776b28_0
  - re2==2020.04.01=he1b5a44_0
  - libgfortran-ng==7.3.0=hdf63c60_5
  - hdf5==1.10.5=nompi_h3c11f04_1104
  - mayavi==4.7.1=py38h7eb8c7e_2
  - numba==0.49.1=py38h0573a6f_0
  - freetype==2.10.1=he06d7ca_0
  - blosc==1.18.1=he1b5a44_0
  - libxml2==2.9.10=hee79883_0
  - vtk==8.2.0=py38h667666d_213
  - hdf4==4.2.13=hf30be14_1003
  - sqlite==3.30.1=hcee41ef_0
  - statsmodels==0.11.1=py38h1e0a361_1
  - dipy==1.1.0=py38hc1659b7_1
  - nspr==4.25=he1b5a44_0
  - libcurl==7.69.1=hf7181ac_0
  - cython==0.29.19=pypi_0
  - traits==6.0.0=py38h1e0a361_1
  - readline==8.0=hf8c457e_0
  - cvxopt==1.2.5=py38hf48cded_1
  - bzip2==1.0.8=h516909a_2
  - gst-plugins-base==1.14.5=h0935bb2_2
  - python==3.8.2=h8356626_5_cpython
  - scikit-learn==0.22.2.post1=py38hcdab131_0
  - pyqt==5.12.3=py38hcca6a23_1
  - libllvm9==9.0.1=hc9558a2_0
  - libssh2==1.8.2=h22169c7_2
  - bitstring==3.1.6=pypi_0
  - dbus==1.13.6=he372182_0
  - pcre==8.44=he1b5a44_0
  - pthread-stubs==0.4=h14c3975_1001
  - jsoncpp==1.8.4=hc9558a2_1002
  - abseil-cpp==20200225.2=he1b5a44_0
  - qt==5.12.5=hd8c4c69_1
  - matplotlib-base==3.2.1=py38h2af1d28_0
  - grpc-cpp==1.28.1=h8e748ff_2
  - xorg-libxt==1.2.0=h516909a_0
  - libstdcxx-ng==9.2.0=hdf63c60_2
  - xorg-xproto==7.0.31=h14c3975_1007
  - numexpr==2.7.1=py38hcb8c335_1
  - libwebp-base==1.1.0=h516909a_3
  - tk==8.6.10=hed695b0_0
  - gettext==0.19.8.1=hc5be6a0_1002
  - libevent==2.1.10=h72c5cf5_0
  - libedit==3.1.20170329=hf8c457e_1001
  - metis==5.1.0=he1b5a44_1005
  - xorg-libxdmcp==1.1.3=h516909a_0
  - libffi==3.2.1=he1b5a44_1007
  - libprotobuf==3.11.4=h8b12597_0
  - libxcb==1.13=h14c3975_1002
  - arrow-cpp==0.16.0=py38h908f8fe_2
  - pyzmq==19.0.1=py38ha71036d_0
  - xorg-libx11==1.6.9=h516909a_0
  - pyqtwebengine==5.12.1=pypi_0
  - xorg-kbproto==1.0.7=h14c3975_1002
  - libxkbcommon==0.10.0=he1b5a44_0
  - zeromq==4.3.2=he1b5a44_2
  - libsodium==1.0.17=h516909a_0
  - gflags==2.2.2=he1b5a44_1002
  - pyarrow==0.16.0=py38h56ab25f_2
  - zlib==1.2.11=h516909a_1006
  - pyrsistent==0.16.0=py38h1e0a361_0
  - glog==0.4.0=h49b9bf7_3
  - fontconfig==2.13.1=h86ecdb6_1001
  - glib==2.58.3=py38h73cb85d_1004
  - pyserial==3.4=pypi_0
  - gstreamer==1.14.5=h36ae1b5_2
  - kiwisolver==1.2.0=py38hbf85e49_0
  - openssl==1.1.1g=h516909a_0
  - xorg-libsm==1.2.3=h84519dc_1000
  - pyqt5-sip==4.19.18=pypi_0
  - glpk==4.65=he80fd80_1002
  - thrift-cpp==0.13.0=h62aa4f2_2
  - lazy-object-proxy==1.4.3=py38h1e0a361_2
  - xorg-libxau==1.0.9=h14c3975_0
  - suitesparse==5.7.2=h717dc36_0
  - gmp==6.2.0=he1b5a44_2
  - expat==2.2.9=he1b5a44_2
  - zstd==1.4.4=h3b9ef0a_2
  - xorg-libice==1.0.10=h516909a_0
  - psutil==5.7.0=py38h1e0a361_1
  - krb5==1.17.1=h2fd8d38_0
  - enum-compat==0.0.3=pypi_0
  - networkx==2.4=pypi_0
  - pylsl==1.12.2=pypi_0
  - brotli==1.0.7=he1b5a44_1001
  - libclang==9.0.1=default_hde54327_0
  - netcdf4==1.5.3=nompi_py38heb6102f_103
  - dsdp==5.8=h23d7751_1203
  - numpy==1.18.1=py38h8854b6b_1
  - fftw==3.3.8=nompi_h7f3a6c3_1110
  - jpeg==9c=h14c3975_1001
  - scipy==1.4.1=py38h18bccfc_2
  - _openmp_mutex==4.5=1_llvm
  - mistune==0.8.4=py38h1e0a361_1001
  - lz4-c==1.8.3=he1b5a44_1001
  - libtiff==4.1.0=hc7e4089_6
  - cftime==1.1.3=py38h8790de6_0
  - pytables==3.6.1=py38h9f153d1_1
  - libiconv==1.15=h516909a_1006
  - aws-sdk-cpp==1.7.164=hc831370_1
  - pygatt==4.0.5=pypi_0
  - llvmlite==0.32.1=py38hd408876_0
  - snappy==1.1.8=he1b5a44_1
  - libgcc-ng==9.2.0=h24d8f2e_2
  - curl==7.69.1=h33f0ec9_0
  - libnetcdf==4.7.4=nompi_h9f9fd6a_101
  - ld_impl_linux-64==2.34=h53a641e_0
  - libuuid==2.32.1=h14c3975_1000
  - nss==3.47=he751ad9_0
  - tbb==2020.1=hc9558a2_0
  - h5py==2.10.0=nompi_py38h513d04c_102
  - ncurses==6.1=hf484d3e_1002
  - c-ares==1.15.0=h516909a_1001
  - libpng==1.6.37=hed695b0_1
  - icu==64.2=he1b5a44_1
  - _libgcc_mutex==0.1=conda_forge
  - llvm-openmp==9.0.1=hc9558a2_2
  - pandas==1.0.3=py38hcb8c335_0
  - wrapt==1.12.1=py38h1e0a361_1
  - libopenblas==0.3.9=h5ec1e0e_0
  - nsrl==0.1.1=pypi_0
  - xz==5.2.4=h516909a_1002
  - tornado==6.0.4=py38h1e0a361_1
  - lzo==2.10=h14c3975_1000

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by benyaminmk** [comment]
tested with python 3.8 on windows and it's working. 

What worked for me:
1. create new conda env called 'neuromusic' with python 3.8 (`conda create -n neuromusic python=3.8`)
2. activate the new environment (`conda activate neuromusic`)
3. install requirements using pip (`pip install -r requirements.txt`)
